function stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)

minVi=9.5
maxVi=40

minVoLow=3
maxVoLow=7.5

minVoHigh=7.5
maxVoHigh=37

minimRs=1;
maximRs=10000;

Vref = 7.5

T = table([200;220;240;270;300;330;360;390;430;470;510;560;620;680;750;820;910; ...
    1000;1100;1200;1300;1500;1600;1800;2000;2200;2400;2700;3000;3600;3900; ...
    4300;4700;5100;5600;6200;6800;7500;8200;9100;10000;11000;12000;13000; ...
    15000;16000;18000;20000;24000;27000],'VariableNames', {'Rezistenta'});

Vi_Array = 9.5:0.1:40

Vo_values = zeros(1,length(Vi_Array))

figura = figure('Name','Stabilizator LM723',...
'units','normalized',...
'position',[0.1 0.1 0.8 0.8],...
'numbertitle','off')

f=uimenu('Label','Proiect');
 uimenu(f,'Label','Documentatie','Callback','open Documentatie_Butica_Cristian.pdf');

if Vi > maxVi
    Vi = maxVi
elseif Vi < minVi
    Vi = minVi
end

if Vi <= Vo
    Vo=Vi-2;
end

Bp_u=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.8 0.8 0.14 0.05],...
'value',state,...
'String','Low Voltage Regulation(3-6.9V)|High Voltage Regulation(8-37V)',...
'Callback','state=(get(gco,''value''));close;stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

switch state

case 1

if Vo >= maxVoLow
    Vo = maxVoLow-0.1
elseif Vo < minVoLow
    Vo = minVoLow
end

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.80 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vi[V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.8 0.1 0.05],...
          'String',Vi,...
          'Callback','Vi=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.35 0.85 0.30 0.05],...
          'FontSize',12,...
          'String','Introduceti valoarea pentru R1[ohm] =');



R1 = calculR1(R1,T);

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.45 0.8 0.1 0.05],...
          'String',R1,...
          'Callback','R1=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.7 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vo[V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.7 0.1 0.05],...
          'String',Vo,...
          'Callback','Vo=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

R2 = (-1*Vo*R1)/(Vo-Vref);
R2 = calculR2(R2,T);

for i=1:length(Vi_Array)
    Vo_values(i) = (R2*Vref)/(R1+R2);
end

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.6 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vo real [V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.6 0.1 0.05],...
          'String',(R2*Vref)/(R1+R2),...
          'Callback','close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.35 0.72 0.30 0.05],...
          'FontSize',12,...
          'String','Pentru stabilizarea curenta avem nevoie de R2[ohm] =');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.45 0.67 0.1 0.05],...
          'String',R2,...
          'Callback','R2=str2num(get(gco,''string''))');

stabil_low = imread('low_voltage_regulator.png');
coordonate = axes('Parent', figura, 'Units', 'pixels', 'Position', [25, 80, 738, 263]);

img = imshow(stabil_low, 'Parent', coordonate);

ck1=uicontrol('Style','check',...
          'Units','normalized',...
          'Position',[0.8 0.6 0.1 0.05],...
          'String','Load Regulation',...
          'Value',0,...
          'Callback','grafic=1,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

if grafic == 1
    img.Visible = 'off'
    stabil_low = imread('low_load.png');
    coordonate = axes('Parent', figura, 'Units', 'pixels', 'Position', [25, 55, 854, 330]);
    imshow(stabil_low, 'Parent', coordonate);
    
    if Rs > maximRs
        Rs = maximRs
    elseif Rs < minimRs
        Rs = minimRs
    end

    uicontrol('Style','slider',...
          'Units','normalized',...
          'Position',[0.35 0.55 0.3 0.05],...
          'Value',Rs,...
          'Min',minimRs,'Max',maximRs,...
          'SliderStep',[10/(maximRs-minimRs) 10/(maximRs-minimRs)],...
          'Callback','Rs=round(get(gcbo,''value'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.33 0.55 0.02 0.05],...
          'FontSize',14,...
          'String','1');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.65 0.55 0.07 0.05],...
          'FontSize',14,...
          'String','10K [ohm]');

    uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.46 0.60 0.1 0.05],...
          'String',Rs,...
          'Callback','Rs=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.43 0.60 0.03 0.05],...
          'FontSize',14,...
          'String','Rs');

    VoReal = (R2*Vref)/(R1+R2);

    Is_Array = 0:0.01:150 %% mA

    Vo_Load = zeros(size(Is_Array))

    loadRegulation(VoReal,Is_Array,Vo_Load, Rs)

    set(ck1,'Callback','grafic=0,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)')
    set(ck1,'string','Line Regulation')
else
    lineRegulation(Vi_Array, Vo_values)
    set(ck1,'Callback','grafic=1,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)')
end

case 2

if Vo > maxVoHigh
    Vo = maxVoHigh
elseif Vo < minVoHigh
    Vo = minVoHigh
end

R2 = (R1*(Vo-Vref))/Vref;
R2 = calculR2(R2,T);

for i=1:length(Vi_Array)
    if Vi_Array(i)<=Vo
        Vo_Aux = Vi_Array(i)-2;
        R2_Aux=(R1*(Vo_Aux-Vref))/Vref;
        R2_Aux = calculR2(R2_Aux,T);
        Vo_values(i) = Vref*(1+R2_Aux/R1)
    else
        Vo_values(i) = Vref*(1+R2/R1)
    end
end

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.80 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vi[V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.8 0.1 0.05],...
          'String',Vi,...
          'Callback','Vi=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.35 0.85 0.30 0.05],...
          'FontSize',12,...
          'String','Introduceti valoarea pentru R1[ohm] =');

R1 = calculR1(R1,T)

uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.45 0.8 0.1 0.05],...
          'String',R1,...
          'Callback','R1=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');
uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.7 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vo[V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.7 0.1 0.05],...
          'String',Vo,...
          'Callback','Vo=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.05 0.6 0.1 0.05],...
          'BackgroundColor',[0.75 0.75 0.75],...
          'FontSize',16,...
          'String','Vo real [V]');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.15 0.6 0.1 0.05],...
          'String',Vref*(1+R2/R1),...
          'Callback','close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.35 0.72 0.30 0.05],...
          'FontSize',12,...
          'String','Pentru stabilizarea curenta avem nevoie de R2[ohm] =');
uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.45 0.67 0.1 0.05],...
          'String',R2,...
          'Callback','R2=str2num(get(gco,''string''))');

stabil_high = imread('high_voltage_regulator.png');
coordonate = axes('Parent', figura, 'Units', 'pixels', 'Position', [25, 80, 787, 291]);

img = imshow(stabil_high, 'Parent', coordonate);

ck1=uicontrol('Style','check',...
          'Units','normalized',...
          'Position',[0.8 0.6 0.1 0.05],...
          'String','Load Regulation',...
          'Value',0,...
          'Callback','grafic=1,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

if grafic == 1
    img.Visible = 'off'
    stabil_low = imread('high_load.png');
    coordonate = axes('Parent', figura, 'Units', 'pixels', 'Position', [25, 55, 854, 330]);
    imshow(stabil_low, 'Parent', coordonate);
    
    if Rs > maximRs
        Rs = maximRs
    elseif Rs < minimRs
        Rs = minimRs
    end

    uicontrol('Style','slider',...
          'Units','normalized',...
          'Position',[0.35 0.55 0.3 0.05],...
          'Value',Rs,...
          'Min',minimRs,'Max',maximRs,...
          'SliderStep',[10/(maximRs-minimRs) 10/(maximRs-minimRs)],...
          'Callback','Rs=round(get(gcbo,''value'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.33 0.55 0.02 0.05],...
          'FontSize',14,...
          'String','1');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.65 0.55 0.07 0.05],...
          'FontSize',14,...
          'String','10K [ohm]');

    uicontrol('Style','edit',...
          'Units','normalized',...
          'Position',[0.46 0.60 0.1 0.05],...
          'String',Rs,...
          'Callback','Rs=str2num(get(gco,''string'')),close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)');

    uicontrol('Style','text',...
          'Units','normalized',...
          'BackgroundColor',[0.75 0.75 0.75],...
          'Position',[0.43 0.60 0.03 0.05],...
          'FontSize',14,...
          'String','Rs');

    VoReal = Vref*(1+R2/R1);

    Is_Array = 0:0.01:150 %% mA

    Vo_Load = zeros(size(Is_Array))

    loadRegulation(VoReal,Is_Array,Vo_Load, Rs)

    set(ck1,'Callback','grafic=0,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)')
    set(ck1,'string','Line Regulation')
else
    lineRegulation(Vi_Array, Vo_values)
    set(ck1,'Callback','grafic=1,close,stabilizator_LM723(Vi,Vo,R1,state,grafic,Rs)')
end

end

end


